### ISSUE TITLE
Implement subclasses of Array (IntArray, BoolArray, FloatArray, StringArray)

### ISSUE THREAD

**Issue by brycedewitt** [sidg54/ganguri-irudarayaj-a1-p2#3]
For our implementation of your API, we're placing special emphasis on both speed and efficiency of all our data structures.  As such, my partner and I agree that it makes more sense to implement an Array superclass that outlines all the methods of a generic array, then implementing the actual logic for them in subarrays based on their type (meaning an instantiation of an `IntArray` would only be able to contain ints).  This would allow:

- Greater space efficiency (no need to box primitive types)
- Greater speed (no need to check object types before running operations)

The obvious drawback of this is that we would not be able to create Arrays with multiple datatypes, but our team has decided that the requirements don't actually call for that and that the speed and space improvements are significant enough to support it (Piazza post here: https://piazza.com/class/k51bluky59n2jr?cid=331).

Please add the required files and stubs, as well as update the test file to support those changes).

**Comment by sidg54** [comment]
Wouldn't a wrapper class which extend the Object class for each of the types be a better solution for this?

**Comment by brycedewitt** [comment]
I can see it going either way (another discussion here: https://piazza.com/class/k51bluky59n2jr?cid=369), but at this point it seems like the class sentiment is just to wrap primitives so I'm fine with that just to make everything a lot more compatible.

I'll close this issue.

**Comment by sidg54** [comment]
Added primitive wrapper classes in primitives.h and new tests for Array. (as well as add since that was missing from the original interface).
