### ISSUE TITLE
Use instructors' Object and String classes

### ISSUE THREAD

**Issue by Gavazzi1** [sidg54/ganguri-irudarayaj-a1-p2#4]
Will you please the Object and String classes the instructors provided on Piazza?

https://github.com/chasebish/cwc_object_string

**Comment by sidg54** [comment]
Sure thing, changing it now, will update here after pushing changes.

**Comment by sidg54** [comment]
Made the requested changes. Please see in the current repo or at https://github.com/sidg54/ganguri-irudarayaj-a1-p2/commit/6f5b7cacce2dbe86d97f8024deb2b5b083a3eec4. Closing this issue for now but please let us know if there are any problems with the tests or the code.
