### ISSUE TITLE
Request: have Array constructor take const char* input

### ISSUE THREAD

**Issue by Gavazzi1** [sidg54/ganguri-irudarayaj-a1-p2#5]
g++ outputs this when you make pass a string constant to an Array constructor.

warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]                                                                                                                                Array * a = new Array("Object");

It doesn't break the code, but it would be nice to have no warnings

**Comment by sidg54** [comment]
Thank you for raising this issue, will look into it ASAP.

**Comment by sidg54** [comment]
Just pushed a fix. It also contains a few changes such as an add method for Array, a new set of wrapper classes for primitives and tests for these. Please create an issue if this causes any issues.
