### ISSUE TITLE
A few tests to fix....

### ISSUE THREAD

**Issue by brycedewitt** [sidg54/ganguri-irudarayaj-a1-p2#6]
In `test-array.cpp`, we have a few updates to look at, I think they were mostly just typos but let me know if we're missing anything (entirely possible):

- Line 43: I assume `a->...` should be changed to `a2->...`

- Line 52: `... != 2` instead of `... != 3` since it even says that in the error

- Line 67: `.. != 1` instead of `... != 2` since the previous test checks for length 2, then does a `remove` function

With those updates our implementation passes so let us know if you have any issues there

**Comment by sidg54** [comment]
You are absolutely correct about this, I have a push coming, will update here after pushing these changes, thank you!

**Comment by sidg54** [comment]
The test fixes can be found at https://github.com/sidg54/ganguri-irudarayaj-a1-p2/commit/6246482a5612346743b6b56e1ded05fe5a7a9522. Closing this for now but please let us know if there are any other problems.

**Comment by brycedewitt** [comment]
Looks good, thanks!
