### ISSUE TITLE
Ownership of pointers

### ISSUE THREAD

**Issue by Gavazzi1** [sidg54/ganguri-irudarayaj-a1-p2#7]
You never mention it in the spec, but who owns the pointer to an object passed to append(), insert(), add(), and set() and returned from get()?

The tests add the same string to multiple arrays, so if all the arrays own the same pointers you can't know who should free them.

**Comment by sidg54** [comment]
You make a very good point, I will look into this ASAP and possibly split things up into different tests. My apologies for the inconvenience. Will update here when the changes are made.

**Comment by sidg54** [comment]
I modified the tests (seehttps://github.com/sidg54/ganguri-irudarayaj-a1-p2/commit/439927176ca21dfe8ae88004c8f9d4e1c515af50) but I am open to discuss what your group thinks is the best action for who owns the pointer.

**Comment by brycedewitt** [comment]
@Gavazzi1 / @sidg54  I don't think my team has much to add here, I agree its ambiguous but I don't have my heart set on any solutions, @Gavazzi1 have you guys already started on one?

**Comment by Gavazzi1** [comment]
Yeah, the way we implemented it, append(), insert(), and add() give ownership of the pointer to the Array. When get() is called, the Array keeps ownership of the pointer. When remove() is called, whoever called it gets ownership of the pointer.

**Comment by sidg54** [comment]
If that's the way it makes most sense, I'm all for doing it that way. Is there anything I can change in terms of the interface besides commenting to update the spec that will help your groups?

**Comment by Gavazzi1** [comment]
Comments alone are fine for us, but we're open to changes if other groups have any

**Comment by sidg54** [comment]
Just added the comments indicating ownership. You can find the changes at https://github.com/sidg54/ganguri-irudarayaj-a1-p2/commit/95429ac38667659304a5f9162fb5b3beb59d8b15
